services:
  chatappapi:
    container_name: chatappapi
    build:
      context: .
      dockerfile: server/src/ChatApp.Api/Dockerfile
    ports:
      - 5154:80
    environment:
      - ConnectionStrings__PostgreSQL=Host=chatappdb;Database=ChatAppDb;Port=5432;Username=postgres;Password=postgres
    depends_on:
      - chatappdb
    networks:
      - chatapp-network
  
  chatappdb:
    image: postgres
    container_name: chatappdb
    restart: always
    environment:
      - POSTGRES_DB=ChatAppDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chatapp-network

volumes:
  pgdata:

networks:
  chatapp-network:
    driver: bridge
